import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileReader;
import java.io.IOException;
import java.sql.*;
import java.util.Objects;
import java.util.Scanner;

public class AlgorithmPanel extends JPanel {
    JLabel employeesLabel, eventsLabel, competencesLabel, del1, del2, del3, del4, timeLabel, mlLabel;
    JButton startAntAlg, startAnnealingAlg, startAllAlg, startSetAlg;
    JProgressBar progressBar;
    AlgorithmPanel() {
        Font font = Main.font;
        employeesLabel = new JLabel("Сотрудников: ");
//        employeesLabel.setPreferredSize(new Dimension(150, 20));
        eventsLabel = new JLabel("Мероприятий: ");
//        eventsLabel.setPreferredSize(new Dimension(150, 20));
        competencesLabel = new JLabel("Компетенций к развитию: ");
//        competencesLabel.setPreferredSize(new Dimension(160, 20));
        timeLabel = new JLabel("Время работы: ");
        mlLabel = new JLabel("Подождите. Идёт анализ данных.");
        employeesLabel.setFont(font);
        eventsLabel.setFont(font);
        competencesLabel.setFont(font);
        mlLabel.setFont(font);
        del1 = new JLabel();
        del1.setPreferredSize(new Dimension(600,20));
        del2 = new JLabel();
        del2.setPreferredSize(new Dimension(600,20));
        del3 = new JLabel();
        del3.setPreferredSize(new Dimension(600,20));
        del4 = new JLabel();
        del4.setPreferredSize(new Dimension(600,20));
        add(employeesLabel);
        add(del1);
        add(eventsLabel);
        add(del2);
        add(competencesLabel);
        add(del3);
        add(mlLabel);
        add(del4);
        startAntAlg = new JButton("Метод муравьиных колоний");
        startAntAlg.setPreferredSize(new Dimension(250, 50));
        startAntAlg.setFont(Main.font);
        startAntAlg.setVisible(false);
        add(startAntAlg);
        startAnnealingAlg = new JButton("Метод имитации отжига");
        startAnnealingAlg.setPreferredSize(new Dimension(250, 50));
        startAnnealingAlg.setFont(Main.font);
        startAnnealingAlg.setVisible(false);
        add(startAnnealingAlg);
        startAllAlg = new JButton("Оба алгоритма");
        startAllAlg.setPreferredSize(new Dimension(450, 50));
        startAllAlg.setFont(Main.font);
        startAllAlg.setVisible(false);
        add(startAllAlg);
        startSetAlg = new JButton(new ImageIcon(Objects.requireNonNull(AlgorithmPanel.class.getResource("tune.png"))));
        startSetAlg.setPreferredSize(new Dimension(50, 50));
        startSetAlg.setFont(Main.font);
        startSetAlg.setVisible(false);
        add(startSetAlg);
        progressBar = new JProgressBar();
        add(progressBar);
        timeLabel.setVisible(false);
        add(timeLabel);
    }
}